# Generated by Django 4.2.2 on 2023-06-13 22:03

from django.db import migrations, models
import shortener.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField()),
                (
                    "short_url_code",
                    models.CharField(
                        default=shortener.models.generate_short_url_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
